const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [  ],
    securityDefinitions: {
        "Bearer": {
          "type": "apiKey",
          "name": "Authorization",
          "in":"header",
          "description": "send JWT"
        }
      },
    definitions: {
        Study: {
          "type": "object",
          "properties": {
            "studyId":{
              "type":"Number"
            },
            "name":{
              "type":"String"
            },
            "schedule":{
              "type":"String"
            },
            "startDate":{
              "type":"String"
            },
            "endJoinDate":{
              "type":"String"
            },
            "writeDate":{
              "type":"String"
            },
            "size":{
              "type":"Number"
            },
            "explain":{
              "type":"String"
            },
            "joinLater":{
              "type":"Boolean"
            },
            "userId":{
              "type":"Number"
            },
            "level":{
              "type":"Number"
            },
            "studyType":{
              "type":"Number"
            },
            "joinNum":{
              "type":"Number"
            }
        }
      },
        StudyComment: {
          "type": "object",
          "properties": {
            "studyCommentId":{
              "type":"Number"
            },
            "studyId":{
              "type":"Number"
            },
            "content":{
              "type":"String"
            },
            "userId":{
              "type":"String"
            },
            "date":{
              "type":"String"
            }
          }
        },
        StudyJoin: {
          "type": "object",
          "properties": {
            "studyId":{
              "type":"Number"
            },
            "userId":{
              "type":"Number"
            },
            "userName":{
              "type":"String"
            },
            "leader":{
              "type":"Boolean"
            }
          }
        }, 
         User: {
          "type": "object",
          "properties": {
            "userId":{
            "type":"Number"
          },
          "group":{
            "type":"Number"
          },
          "email":{
            "type":"String"
          },
          "nickname":{
            "type":"String"
          },
          "password":{
            "type":"String"
          }
        }
        }
      }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routers/*.js','./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc)